### PR TITLE
WIP: Add support for Capistrano 3.0.

### PR DESCRIPTION
**Pull request by johnbellone**
This takes care of #1 too. 

This is the initial cut for Capistrano 3.0 support. I followed many of the recipes provided by default in the new Capistrano versions. You should be able to just add this into your Capfile:

```
require 'capistrano/puma`
```

I am still running some tests locally to make sure it works in all cases. Let me know if you find anything!

### CODE REVIEW

**Comment by johnbellone** [comment]
I did not add the tasks to automatically run after `deploy:start`, etc because assumed since the deploy.rb files are significantly smaller now teams may want to explicitly display these. What are your thoughts @xijo ?

**Comment by shaneog** [comment]
Do you think this will be merged soon?

**Comment by xijo** [comment]
Hello there, already looked into it, would want to do some test runs first. I think somewhen at the weekend it should be merged in. Greets, Joe

**Comment by shaneog** [comment]
:+1: Thanks!

**Comment by johnbellone** [comment]
@xijo Thanks dude.

**Comment by xijo** [comment]
Hey guys,

good news: it looks like puma has builtin capistrano support now, so please have a look at https://github.com/puma/puma#capistrano-deployment

Please let me now if it fits your needs, if so I'd close this repo and add a notice.

**Comment by shaneog** [comment]
It doesn't work with Capistrano v3 (https://github.com/puma/puma/issues/383) and it looks like it's being removed from puma (IMO it shouldn't be there anyway) and moved into it's own gem here https://github.com/seuros/capistrano-puma

**Comment by xijo** [comment]
Alright, merged that and release v0.2.0

**Pull request merged**
